name: backfill-cpes
on: 
  workflow_dispatch:

jobs:
  backfill-cpes-till-2015:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    
    steps:
      - uses: actions/checkout@v3
      - name: Run download-cpes.yml workflow for each year
        run: |
          gh workflow run .github/workflows/download-cpes.yml -f start-date=1990-01-01 -f end-date=2015-01-01
          sleep 1.5h
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
  backfill-cpes-after-2015:
    needs: backfill-cpes-till-2015
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    
    steps:
      - uses: actions/checkout@v3
      - name: Run download-cpes.yml workflow for each year
        run: |
          gh workflow run .github/workflows/download-cpes.yml -f start-date=2015-01-01 -f end-date=$(printf '%(%Y-%m-%d)T\n' -1)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
